config/routes.rb
Demo::Application.routes.draw do
  
  resources :categories_items

  resources :items_users

  resources :categories

  resources :items

  resources :users

  get "static_pages/home"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'static_pages#home'

end

app/models/categories_item.rb
class CategoriesItem < ActiveRecord::Base
end

app/controllers/categories_items_controller.rb
class CategoriesItemsController < ApplicationController
  before_action :set_categories_item, only: [:show, :edit, :update, :destroy]

  # GET /categories_items
  # GET /categories_items.json
  def index
    @categories_items = CategoriesItem.all
  end

  # GET /categories_items/1
  # GET /categories_items/1.json
  def show
  end

  # GET /categories_items/new
  def new
    @categories_item = CategoriesItem.new
  end

  # GET /categories_items/1/edit
  def edit
  end

  # POST /categories_items
  # POST /categories_items.json
  def create
    @categories_item = CategoriesItem.new(categories_item_params)

    respond_to do |format|
      if @categories_item.save
        format.html { redirect_to @categories_item, notice: 'Categories item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @categories_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @categories_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories_items/1
  # PATCH/PUT /categories_items/1.json
  def update
    respond_to do |format|
      if @categories_item.update(categories_item_params)
        format.html { redirect_to @categories_item, notice: 'Categories item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @categories_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories_items/1
  # DELETE /categories_items/1.json
  def destroy
    @categories_item.destroy
    respond_to do |format|
      format.html { redirect_to categories_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categories_item
      @categories_item = CategoriesItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categories_item_params
      params.require(:categories_item).permit(:category_id, :item_id)
    end
end

app/helpers/categories_items_helper.rb
module CategoriesItemsHelper
end

app/views/categories_items/_form.html.erb
<%= form_for(@categories_item) do |f| %>
  <% if @categories_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categories_item.errors.count, "error") %> prohibited this categories_item from being saved:</h2>

      <ul>
      <% @categories_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories_items/edit.html.erb
<h1>Editing categories_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @categories_item %> |
<%= link_to 'Back', categories_items_path %>

app/views/categories_items/index.html.erb
<h1>Listing categories_items</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Item</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories_items.each do |categories_item| %>
      <tr>
        <td><%= categories_item.category_id %></td>
        <td><%= categories_item.item_id %></td>
        <td><%= link_to 'Show', categories_item %></td>
        <td><%= link_to 'Edit', edit_categories_item_path(categories_item) %></td>
        <td><%= link_to 'Destroy', categories_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categories item', new_categories_item_path %>

app/views/categories_items/new.html.erb
<h1>New categories_item</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_items_path %>

app/views/categories_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @categories_item.category_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @categories_item.item_id %>
</p>

<%= link_to 'Edit', edit_categories_item_path(@categories_item) %> |
<%= link_to 'Back', categories_items_path %>